theme: jekyll-theme-minimal
 
<!DOCTYPE html>
<html>
<head>
<head> 
<body>
   <nav class="navbar">
         <div class="brand-title">DC EATS!</div>
         <div class=:navbar-links>
             <ul>
                 <li><a href="#">Home</a></li>
                 <li><a href="#">Georgetown</a></li>
                 <li><a href="#">NOMA</a></li>
                 <li><a href="#">14th Street</a></li>
             </ul>
<h1>Welcome to DC Eats!</h1>
<img src="images.jpg" alt="Washington Header">  

<p1>Attending undergrad and graduate school in Washington DC has allowed me to embrace all the unique restaurants DC has to offer. Going out to new restaurants not only allows you to experience new food but also embrace different DC neighrborhoods. Eating out is a way to explore DC whether you are born and bread washingtonion or new to the district! </p1>
<h2>How to Navigate DC Eats!</h2>
<p2>Restaurant reviews will be categorized by neighrbohoods followed by a 5 star review system. There are a number of factors I take into consideration when performing a review. They include: the ambiance, the food, and the price point of the restaurant. </p2>

<h1>Georgetown</h1>
 <h2>Top Three Hidden Gems in Georgetown</h2>
          <h3>Cafe Leopold's<h3>
           <h5>Ambiance:This european syle like cafe is most likely a spot visitors or locals will miss. Its locatedin Cadey's Alley away from the chaos of mstreet. Customers are transported to what feels like a quaint restaurant in a small european town!<h5>
            <h5>Food: When the DC weather begins to warm up, this is definitely one of my go to brunch spots! The menu has a variety of options that can satisfy anyone's sweet or savory mood. Their brunch drink specials range from a classic mimosa to crafty cocktails! 
             <h5>Price: Whether you are dining for brunch, lunch, or dinner; the prices at Leopolds are a steal for the quality of food you are getting! 
              <h5>Rating: Overall, I give Leopold's Cafe 4 stars out of 5! My one star deduction is mainly due to their service which can be a hit or a miss. 
            <h3> Lutece<h3>
             <h5>Ambiance: This neo french style restaurant is perfect for date nights or a girls night out! This intimate restaurant, gives customers a chance to experience french food in a more casual manner. Individuals are able to see their meal being prepped due to the open kitchen concept. It is the perfect place for young adults and adults to dine! 
              <h5>Food: The best part about Lutece is that it changes its menu due to whats available during the season. This allows the dishes to have the finest ingredients and customers are able to experience new dishes every visit! 
